/**
 * Re-download the self-hosted faces from Google and regenerate src/fonts.css.
 *
 * These are Google's own woff2 files, unmodified. They are deliberately NOT
 * subsetted: a dropped glyph is a worse failure than a few extra kB, and
 * unicode-range already means a browser only fetches the subsets it needs.
 *
 *   npm run fonts
 */
import { writeFileSync, mkdirSync } from 'node:fs'

const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
  + '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
const URL_ = 'https://fonts.googleapis.com/css2'
  + '?family=Archivo:wdth,wght@62..125,400..800'
  + '&family=Instrument+Serif:ital@1'
  + '&family=JetBrains+Mono:wght@400&display=swap'
const KEEP = new Set(['latin', 'latin-ext'])

mkdirSync('public/fonts', { recursive: true })
const css = await (await fetch(URL_, { headers: { 'User-Agent': UA } })).text()

let out = `/* Generated by scripts/fonts.mjs — do not edit by hand.
   Google's own latin/latin-ext woff2, with the descriptors they ship,
   including the variable ranges Archivo needs for its width axis. */\n`

for (const part of css.split('/*').slice(1)) {
  const sub = part.slice(0, part.indexOf('*/')).trim()
  if (!KEEP.has(sub)) continue
  const g = (re) => (part.match(re) || [])[1]?.trim()
  const fam = g(/font-family:\s*'([^']+)'/)
  const src = g(/url\((https:[^)]+)\)/)
  if (!fam || !src) continue
  const style = g(/font-style:\s*([^;]+)/)
  const weight = g(/font-weight:\s*([^;]+)/)
  const stretch = g(/font-stretch:\s*([^;]+)/)
  const range = g(/unicode-range:\s*([^;]+)/)
  const slug = `${fam.toLowerCase().replace(/ /g, '-')}-`
    + `${style === 'italic' ? 'italic-' : ''}${weight.includes(' ') ? 'var' : weight}-${sub}`
  const buf = Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer())
  writeFileSync(`public/fonts/${slug}.woff2`, buf)
  out += `@font-face{font-family:'${fam}';font-style:${style};font-weight:${weight};`
    + (stretch ? `font-stretch:${stretch};` : '')
    + `font-display:swap;src:url(/fonts/${slug}.woff2) format('woff2');`
    + `unicode-range:${range}}\n`
  console.log(`${String((buf.length / 1024) | 0).padStart(4)} kB  ${slug}.woff2`)
}
writeFileSync('src/fonts.css', out)
